CSD2126: Line Class Reference
Line Class Reference
#include <Line.h>
Public Member Functions
Line ()
Line (Vec2 _pt0, Vec2 _pt1)
Line & operator= (const Line &rhs)=default
Line (const Line &rhs)=default
Vec2 Pt0 () const
Vec2 Pt1 () const
Vec2 Normal () const
void SetPt0 (Vec2 v)
void SetPt1 (Vec2 v)
Private Member Functions
void RecalculateLineNormal ()
Private Attributes
Vec2 pt0
Vec2 pt1
Vec2 normal
Detailed Description
Definition at line 8 of file Line.h.
Constructor & Destructor Documentation
Line() [1/3]
Line::Line () inline
Definition at line 14 of file Line.h.
 {}
Line() [2/3]
Line::Line (Vec2 _pt0, Vec2 _pt1) inline
Definition at line 15 of file Line.h.
                              : pt0(_pt0), pt1(_pt1) {
     RecalculateLineNormal();
   }
References RecalculateLineNormal().
Line() [3/3]
Line::Line (const Line & rhs) default
Member Function Documentation
Normal()
Vec2 Line::Normal () const
Definition at line 15 of file Line.cpp.
{
   return normal;
 }
References normal.
Referenced by Collision::Check_AABB_Line(), and Collision::Check_Circle_Line().
operator=()
Line& Line::operator= (const Line & rhs) default
Pt0()
Vec2 Line::Pt0 () const
Definition at line 7 of file Line.cpp.
                      {
   return pt0;
 }
References pt0.
Referenced by Collision::Check_AABB_Line(), Collision::Check_Circle_Line(), and Collision::Check_Circle_LineEdge().
Pt1()
Vec2 Line::Pt1 () const
Definition at line 11 of file Line.cpp.
                      {
   return pt1;
 }
References pt1.
Referenced by Collision::Check_AABB_Line(), Collision::Check_Circle_Line(), and Collision::Check_Circle_LineEdge().
RecalculateLineNormal()
void Line::RecalculateLineNormal () private
Definition at line 3 of file Line.cpp.
{
   normal = Mat3{ 0.f, 1.f, 0.f, -1.f, 0.f, 0.f, 0.f, 0.f, 1.f } *(pt1 - pt0) / sqrt(normal.x * normal.x + normal.y * normal.y);
 }
References normal, pt0, pt1, Vec2::x, and Vec2::y.
Referenced by Line(), SetPt0(), and SetPt1().
SetPt0()
void Line::SetPt0 (Vec2 v)
Definition at line 19 of file Line.cpp.
{
   pt0 = v;
   RecalculateLineNormal();
 }
References pt0, and RecalculateLineNormal().
SetPt1()
void Line::SetPt1 (Vec2 v)
Definition at line 24 of file Line.cpp.
{
   pt1 = v;
   RecalculateLineNormal();
 }
References pt1, and RecalculateLineNormal().
Member Data Documentation
normal
Vec2 Line::normal private
Definition at line 11 of file Line.h.
Referenced by Normal(), and RecalculateLineNormal().
pt0
Vec2 Line::pt0 private
Definition at line 11 of file Line.h.
Referenced by Pt0(), RecalculateLineNormal(), and SetPt0().
pt1
Vec2 Line::pt1 private
Definition at line 11 of file Line.h.
Referenced by Pt1(), RecalculateLineNormal(), and SetPt1().
The documentation for this class was generated from the following files:
include/Line.h
Line.cpp