CSD2126: GLApp Class Reference
GLApp Class Reference
#include <glapp.h>
Classes
struct GLModel
struct GLObject
struct GLViewport
Public Member Functions
GLApp ()
virtual void Initialize ()
virtual void Update (float time)
Public Member Functions inherited from ISystems
virtual void Free ()
virtual void GetSystemName ()
Static Public Member Functions
static void cleanup ()
static void init_scene ()
static GLuint setup_texobj (const char *)
static void insert_shdrpgm (std::string shdr_pgm_name, std::string vtx_shdr, std::string frg_shdr)
Static Public Attributes
static GLModel mdl {}
static std::map< std::string, GLSLShader > shdrpgms
static std::map< std::string, GLModel > models
static std::map< std::string, GLObject > objects
static std::map< std::string, GLuint > textures
Detailed Description
Definition at line 17 of file glapp.h.
Constructor & Destructor Documentation
GLApp()
GLApp::GLApp ()
Definition at line 32 of file glapp.cpp.
 {
   app = this;
 }
References app.
Member Function Documentation
cleanup()
void GLApp::cleanup () static
Definition at line 335 of file glapp.cpp.
 {
 }
init_scene()
void GLApp::init_scene () static
Definition at line 50 of file glapp.cpp.
                       {
   //read file
   std::ifstream ifs("../scenes/game.scn", std::ios::in);
   if (!ifs)
   {
     std::cout <<
       "Error : Unable to open scene file : " << std::endl;
     exit(EXIT_FAILURE);
   }
   ifs.seekg(0, std::ios::beg);
   std::string line;
   getline(ifs, line);
   std::istringstream line_sstm{ line };
   int obj_cnt;
   line_sstm >> obj_cnt;
   while (obj_cnt--)
   {
     GLObject Object;
     // line 1   model name
     getline(ifs, line);
     std::istringstream line_model_name{ line };
     std::string model_name;
     line_model_name >> model_name;
     // if model with name model_name is not present in std::map container
     //called models, then add this model to the container
     if (models.find(model_name) != models.end())
     {
       Object.mdl_ref = models.find(model_name);
     }
     else
     {
       GLModel Model;
       // Read from meshes files
       std::ifstream ifs_msh{ "../meshes/" + model_name + ".msh", std::ios::in };
       if (!ifs_msh)
       {
         std::cout << "ERROR: Unable to open mesh file: "
           << model_name << "\n";
         exit(EXIT_FAILURE);
       }
       ifs_msh.seekg(0, std::ios::beg);
       std::string line_mesh;
       getline(ifs_msh, line_mesh);
       std::istringstream line_sstm_mesh{ line_mesh };
       char obj_prefix;
       std::string mesh_name;
       line_sstm_mesh >> obj_prefix >> mesh_name;
       std::vector < float > pos_vtx;
       std::vector < float > clr_vtx;
       std::vector < float > tex_coor;
       std::vector < GLushort > gl_tri_primitives;
       GLuint vbo, vao, ebo;
       while (getline(ifs_msh, line_mesh))
       {
         std::istringstream line_sstm_mdl{ line_mesh };
         line_sstm_mdl >> obj_prefix;
         float float_data;
         GLushort glushort_data;
         if (obj_prefix == 'v')
         {
           while (line_sstm_mdl >> float_data)
           {
             pos_vtx.push_back(float_data);
           }
         }
         if (obj_prefix == 'c')
         {
           while (line_sstm_mdl >> float_data)
           {
             clr_vtx.push_back(float_data);
           }
         }
         if (obj_prefix == 'x')
         {
           while (line_sstm_mdl >> float_data)
           {
             tex_coor.push_back(float_data);
           }
         }
         if (obj_prefix == 't')
         {
           while (line_sstm_mdl >> glushort_data)
           {
             gl_tri_primitives.push_back(glushort_data);
           }
           Model.primitive_type = GL_TRIANGLES;
         }
       }
         // Set VAO
       glCreateBuffers(1, &vbo);
       glNamedBufferStorage(vbo, sizeof(glm::vec2) * pos_vtx.size() + sizeof(glm::vec3) * clr_vtx.size() + sizeof(glm::vec2) * tex_coor.size(), nullptr, GL_DYNAMIC_STORAGE_BIT);
       glNamedBufferSubData(vbo, 0, sizeof(glm::vec2) * pos_vtx.size(), pos_vtx.data());
       glNamedBufferSubData(vbo, sizeof(glm::vec2) * pos_vtx.size(), sizeof(glm::vec3) * clr_vtx.size(), clr_vtx.data());
       glNamedBufferSubData(vbo, sizeof(glm::vec2) * pos_vtx.size() + sizeof(glm::vec3) * clr_vtx.size(),
         sizeof(glm::vec2) * tex_coor.size(), tex_coor.data());
       glCreateVertexArrays(1, &vao);
       glEnableVertexArrayAttrib(vao, 0);
       glVertexArrayVertexBuffer(vao, 0, vbo, 0, sizeof(glm::vec2));
       glVertexArrayAttribFormat(vao, 0, 2, GL_FLOAT, GL_FALSE, 0);
       glVertexArrayAttribBinding(vao, 0, 0);
       glEnableVertexArrayAttrib(vao, 1);
       glVertexArrayVertexBuffer(vao, 1, vbo, sizeof(glm::vec2) * pos_vtx.size(), sizeof(glm::vec3));
       glVertexArrayAttribFormat(vao, 1, 3, GL_FLOAT, GL_FALSE, 0);
       glVertexArrayAttribBinding(vao, 1, 1);
       glEnableVertexArrayAttrib(vao, 2);
       glVertexArrayVertexBuffer(vao, 2, vbo, sizeof(glm::vec2) * pos_vtx.size() + sizeof(glm::vec3) * clr_vtx.size(), sizeof(glm::vec2));
       glVertexArrayAttribFormat(vao, 2, 2, GL_FLOAT, GL_FALSE, 0);
       glVertexArrayAttribBinding(vao, 2, 2);
       glCreateBuffers(1, &ebo);
       glNamedBufferStorage(ebo, sizeof(GLushort) * gl_tri_primitives.size(), gl_tri_primitives.data(), GL_DYNAMIC_STORAGE_BIT);
       glVertexArrayElementBuffer(vao, ebo);
       glBindVertexArray(0);
       Model.vaoid = vao;
       Model.primitive_cnt = gl_tri_primitives.size();
       Model.draw_cnt = gl_tri_primitives.size();
       models[model_name] = Model;
       Object.mdl_ref = models.find(model_name);
     }
     std::cout << "model name: " << model_name << std::endl;
     // line2  object number
     getline(ifs, line);
     std::istringstream line_model_obj_num{ line };
     std::string model_object;
     line_model_obj_num >> model_object;
     std::cout << "object: " << model_object << std::endl;
     // line3 object texture
     getline(ifs, line);
     std::istringstream line_model_texture{ line };
     std::string model_texture;
     line_model_texture >> model_texture;
     if (textures.find(model_texture) != textures.end()) {
       Object.tex_ref = textures.find(model_texture);
     }
     else {
       GLuint Texture;
       std::string texture_file = "../Assest/Picture/" + model_texture + ".png";
       Texture = setup_texobj(texture_file.c_str());
       textures[model_texture] = Texture;
       Object.tex_ref = textures.find(model_texture);
     }
     std::cout << "texture: " << model_texture << std::endl;
     //line 4  object shader program
     getline(ifs, line);
     std::istringstream line_model_obj_shader{ line };
     std::string object_shader_program, object_shader_vertex, object_shader_fragment;
     line_model_obj_shader >> object_shader_program;
     line_model_obj_shader >> object_shader_vertex;
     line_model_obj_shader >> object_shader_fragment;
     //if shader program listed in the scene file is not present in
     //std::map container called shdrpgms, then add this model to the container
     if (shdrpgms.find(object_shader_program) != shdrpgms.end())
     {
       Object.shd_ref = shdrpgms.find(object_shader_program);
     }
     else
     {
       insert_shdrpgm(object_shader_program, object_shader_vertex, object_shader_fragment);
       Object.shd_ref = shdrpgms.find(object_shader_program);
     }
     std::cout << "shader program: " << object_shader_program << std::endl;
     //line 5 position
     getline(ifs, line);
     std::istringstream line_model_obj_pos{ line };
     line_model_obj_pos >> Object.position.x >> Object.position.y;
     Object.position.x *= 2.f / window->width;
     Object.position.y *= 2.f / window->height;
     std::cout << "position: " << Object.position.x << " " << Object.position.y << std::endl;
     //line 6 scale
     getline(ifs, line);
     std::istringstream line_model_obj_scale{ line };
     line_model_obj_scale >> Object.scaling.x >> Object.scaling.y;
     Object.scaling.x /= window->width;
     Object.scaling.y /= window->height;
     std::cout << "scale: " << Object.scaling.x << " " << Object.scaling.y << std::endl;
     //line 7 orientation
     getline(ifs, line);
     std::istringstream line_model_obj_orientation{ line };
     line_model_obj_orientation >> Object.orientation;
     Object.orientation *= 3.14159f/180.f;
     std::cout << "orientation: " << Object.orientation << std::endl;
     objects[model_object] = Object;
   }
 }
References GLApp::GLModel::draw_cnt, GLWindow::height, insert_shdrpgm(), line, GLApp::GLObject::mdl_ref, models, objects, GLApp::GLObject::orientation, GLApp::GLObject::position, GLApp::GLModel::primitive_cnt, GLApp::GLModel::primitive_type, GLApp::GLObject::scaling, setup_texobj(), GLApp::GLObject::shd_ref, shdrpgms, GLApp::GLObject::tex_ref, textures, GLApp::GLModel::vaoid, GLWindow::width, and window.
Referenced by Initialize().
Initialize()
void GLApp::Initialize () virtual
Reimplemented from ISystems.
Definition at line 37 of file glapp.cpp.
 {
   glClearColor(1.f, 1.f, 1.f, 1.f);
   glViewport(0, 0, window->width, window->height);
   init_scene();
   // enable alpha blending
   glEnable(GL_BLEND);
   glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
 }
References GLWindow::height, init_scene(), GLWindow::width, and window.
insert_shdrpgm()
void GLApp::insert_shdrpgm (std::string shdr_pgm_name, std::string vtx_shdr, std::string frg_shdr) static
Definition at line 371 of file glapp.cpp.
 {
   std::vector<std::pair<GLenum, std::string>> shdr_files
   {
     std::make_pair(GL_VERTEX_SHADER, vtx_shdr),
     std::make_pair(GL_FRAGMENT_SHADER, frg_shdr)
   };
   GLSLShader shdr_pgm;
   shdr_pgm.CompileLinkValidate(shdr_files);
   if (GL_FALSE == shdr_pgm.IsLinked())
   {
     std::cout << "Unable to compile/link/validate shader programs\n";
     std::cout << shdr_pgm.GetLog() << "\n";
     std::exit(EXIT_FAILURE);
   }
   // add compiled, linked, and validated shader program to
   // std::map container GLApp::shdrpgms
   GLApp::shdrpgms[shdr_pgm_name] = shdr_pgm;
 }
References GLSLShader::CompileLinkValidate(), GLSLShader::GetLog(), GLSLShader::IsLinked(), and shdrpgms.
Referenced by init_scene().
setup_texobj()
GLuint GLApp::setup_texobj (const char * pathname) static
Definition at line 340 of file glapp.cpp.
 {
   int width{ }, height{  }, image_channels;
   unsigned char* ptr_texels = stbi_load(pathname, &width, &height, &image_channels, STBI_rgb_alpha);
   if (!ptr_texels)
   {
     std::cout << "Unable to load texture file: " << pathname << "\n";
     std::exit(EXIT_FAILURE);
   }
   else {
     std::cout << "Loaded texture file: " << pathname << "\n";
     std::cout << "Image width: " << width << "\n";
     std::cout << "Image height: " << height << "\n";
   }
   GLuint texobj_hdl;
   // define and initialize a handle to texture object that will
   // encapsulate two-dimensional textures
   glCreateTextures(GL_TEXTURE_2D, 1, &texobj_hdl);
   // allocate GPU storage for texture image data loaded from file
   glTextureStorage2D(texobj_hdl, 1, GL_RGBA8, width, height);
   // copy image data from client memory to GPU texture buffer memory
   glTextureSubImage2D(texobj_hdl, 0, 0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, ptr_texels);
   // client memory not required since image is buffered in GPU memory
   delete[] ptr_texels;
   return texobj_hdl;
 }
Referenced by init_scene().
Update()
void GLApp::Update (float time) virtual
Implements ISystems.
Definition at line 308 of file glapp.cpp.
 {
   // update all objects
   for (std::map <std::string, GLObject> ::iterator obj = objects.begin(); obj != objects.end(); ++obj)
   {
     obj->second.update();
   }
   glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
   // clear back buffer as before
   glClear(GL_COLOR_BUFFER_BIT);
   std::stringstream sstr;
   sstr <<window->title <<" FPS: " << window->fps;
   glfwSetWindowTitle(window->ptr_window, sstr.str().c_str());
   // draw all objects
   for (std::map <std::string, GLObject> ::iterator obj = objects.begin(); obj != objects.end(); ++obj)
   {
     obj->second.draw();
   }
   glfwSwapBuffers( window->ptr_window);
 }
References GLWindow::fps, objects, GLWindow::ptr_window, GLWindow::title, and window.
Member Data Documentation
mdl
GLApp::GLModel GLApp::mdl {} static
Definition at line 41 of file glapp.h.
models
std::map< std::string, GLApp::GLModel > GLApp::models static
Definition at line 69 of file glapp.h.
Referenced by init_scene().
objects
std::map< std::string, GLApp::GLObject > GLApp::objects static
Definition at line 70 of file glapp.h.
Referenced by init_scene(), and Update().
shdrpgms
std::map< std::string, GLSLShader > GLApp::shdrpgms static
Definition at line 68 of file glapp.h.
Referenced by init_scene(), and insert_shdrpgm().
textures
std::map< std::string, GLuint > GLApp::textures static
Definition at line 71 of file glapp.h.
Referenced by init_scene().
The documentation for this class was generated from the following files:
include/Graphic_gl/glapp.h
src/graphic_gl/glapp.cpp