CSD2126: GLWindow Class Reference
GLWindow Class Reference
#include <GLWindow.h>
Public Member Functions
GLWindow (GLint w, GLint h, std::string t)
virtual void Initialize ()
virtual void Update (float time)
Public Member Functions inherited from ISystems
virtual void Free ()
virtual void GetSystemName ()
Static Public Member Functions
static void ActivateWindow ()
static void cleanup ()
static void error_cb (int error, char const *description)
static void fbsize_cb (GLFWwindow *ptr_win, int wwidth, int hheight)
static void update_time (double fpsCalcInt=1.0)
static void print_specs ()
Static Public Attributes
static GLint width
static GLint height
static GLdouble fps
static GLdouble delta_time
static std::string title
static GLFWwindow * ptr_window
Detailed Description
Definition at line 28 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow()
GLWindow::GLWindow (GLint w, GLint h, std::string t)
Definition at line 32 of file GLWindow.cpp.
{
   GLWindow::width = w;
   GLWindow::height = h;
   GLWindow::title = t;
 }
References height, title, w, and width.
Member Function Documentation
ActivateWindow()
void GLWindow::ActivateWindow () static
Definition at line 111 of file GLWindow.cpp.
 {
 }
Referenced by main().
cleanup()
void GLWindow::cleanup () static
cleanup
Parameters
none
Returns
none
For now, there are no resources allocated by the application program. The only task is to have GLFW return resources back to the system and gracefully terminate.
Definition at line 128 of file GLWindow.cpp.
{
     glfwTerminate();
 }
error_cb()
void GLWindow::error_cb (int error, char const * description) static
error_cb
Parameters
int GLFW error code
@parm char const* Human-readable description of the code
Returns
none
The error callback receives a human-readable description of the error and (when possible) its cause.
Definition at line 148 of file GLWindow.cpp.
{
     (void)error;
 #ifdef _DEBUG
     std::cerr << "GLFW error: " << description << std::endl;
 #endif
 }
Referenced by Initialize().
fbsize_cb()
void GLWindow::fbsize_cb (GLFWwindow * ptr_win, int wwidth, int hheight) static
fbsize_cb
Parameters
GLFWwindow* Handle to window that is being resized
@parm int Width in pixels of new window size
@parm int Height in pixels of new window size
Returns
none
This function is called when the window is resized - it receives the new size of the window in pixels.
Definition at line 172 of file GLWindow.cpp.
{
     (void)ptr_win;
 #ifdef _DEBUG
     std::cout << "fbsize_cb getting called!!!" << std::endl;
 #endif
     // use the entire framebuffer as drawing region
     glViewport(0, 0, wwidth, hheight);
 }
Referenced by Initialize().
Initialize()
void GLWindow::Initialize () virtual
init
Parameters
GLint width
GLint height Dimensions of window requested by program
Reimplemented from ISystems.
Definition at line 48 of file GLWindow.cpp.
{
     // Part 1
     if (!glfwInit()) {
         std::cout << "GLFW init has failed - abort program!!!" << std::endl;
         return;
     }
     // In case a GLFW function fails, an error is reported to callback function
     glfwSetErrorCallback(GLWindow::error_cb);
     // Before asking GLFW to create an OpenGL context, we specify the minimum constraints
     // in that context:
     glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
     glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
     glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
     glfwWindowHint(GLFW_DOUBLEBUFFER, GLFW_TRUE);
     glfwWindowHint(GLFW_RED_BITS, 8); glfwWindowHint(GLFW_GREEN_BITS, 8);
     glfwWindowHint(GLFW_BLUE_BITS, 8); glfwWindowHint(GLFW_ALPHA_BITS, 8);
     glfwWindowHint(GLFW_RESIZABLE, GL_FALSE); // window dimensions are static
     GLWindow::ptr_window = glfwCreateWindow(width, height, title.c_str(), NULL, NULL);
     if (!window->ptr_window) {
         std::cerr << "GLFW unable to create OpenGL context - abort program\n";
         glfwTerminate();
         return;
     }
     glfwMakeContextCurrent(GLWindow::ptr_window);
     glfwSetFramebufferSizeCallback(GLWindow::ptr_window, GLWindow::fbsize_cb);
     input::Init(GLWindow::ptr_window);
     // this is the default setting ...
     glfwSetInputMode(GLWindow::ptr_window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
     // Part 2: Initialize entry points to OpenGL functions and extensions
     GLenum err = glewInit();
     if (GLEW_OK != err) {
         std::cerr << "Unable to initialize GLEW - error: "
             << glewGetErrorString(err) << " abort program" << std::endl;
         return;
     }
     if (GL_VERSION_4_5) {
         std::cout << "Using glew version: " << glewGetString(GLEW_VERSION) << std::endl;
         std::cout << "Driver supports OpenGL 4.5\n" << std::endl;
     }
     else {
         std::cerr << "Driver doesn't support OpenGL 4.5 - abort program" << std::endl;
         return;
     }
 }
References error_cb(), fbsize_cb(), height, input::Init(), ptr_window, title, width, and window.
print_specs()
void GLWindow::print_specs () static
print_specs()
Parameters
none Print usefulvinformation about OpenGL context and graphics hardware to standard output
Definition at line 230 of file GLWindow.cpp.
{
     GLubyte const* str_vendor = glGetString(GL_VENDOR);
     GLubyte const* str_renderer = glGetString(GL_RENDERER);
     GLubyte const* str_version = glGetString(GL_VERSION);
     GLubyte const* str_shader_version = glGetString(GL_SHADING_LANGUAGE_VERSION);
     std::cout << "GPU Vendor: " << str_vendor << std::endl;
     std::cout << "GL Renderer: " << str_renderer << std::endl;
     std::cout << "GL Version: " << str_version << std::endl;
     std::cout << "GL Shader Version: " << str_shader_version << std::endl;
     // Print major and minor version
     GLint major_version, minor_version;
     glGetIntegerv(GL_MAJOR_VERSION, &major_version);
     glGetIntegerv(GL_MINOR_VERSION, &minor_version);
     std::cout << "GL Major Version: " << major_version << std::endl;
     std::cout << "GL Minor Version: " << minor_version << std::endl;
     // Print double buffering information
     GLint double_buffered;
     glGetIntegerv(GL_DOUBLEBUFFER, &double_buffered);
     std::cout << "Current OpenGL Context is " << (double_buffered ? "double buffered" : "not double buffered") << std::endl;
     // Print maximum vertex count
     GLint max_vertex_count;
     glGetIntegerv(GL_MAX_ELEMENTS_VERTICES, &max_vertex_count);
     std::cout << "Maximum Vertex Count: " << max_vertex_count << std::endl;
     // Print maximum indices count
     GLint max_indices_count;
     glGetIntegerv(GL_MAX_ELEMENTS_INDICES, &max_indices_count);
     std::cout << "Maximum Indices Count: " << max_indices_count << std::endl;
     // Print maximum texture size
     GLint max_texture_size;
     glGetIntegerv(GL_MAX_TEXTURE_SIZE, &max_texture_size);
     std::cout << "GL Maximum texture size: " << max_texture_size << std::endl;
     // Print maximum viewport dimensions
     GLint max_viewport_dimensions[2];
     glGetIntegerv(GL_MAX_VIEWPORT_DIMS, max_viewport_dimensions);
     std::cout << "Maximum Viewport Dimensions: " << max_viewport_dimensions[0] << " x " << max_viewport_dimensions[1] << std::endl;
 }
Referenced by main().
Update()
void GLWindow::Update (float time) virtual
Implements ISystems.
Definition at line 102 of file GLWindow.cpp.
 {
     glfwPollEvents();
     // Part 2
     GLWindow::update_time(1.0);
 }
References update_time().
update_time()
void GLWindow::update_time (double fps_calc_interval = 1.0) static
update_time
Parameters
double fps_calc_interval: the interval (in seconds) at which fps is to be calculated
This function must be called once per game loop. It uses GLFW's time functions to compute:
the interval in seconds between each frame
the frames per second every "fps_calc_interval" seconds
Definition at line 194 of file GLWindow.cpp.
{
     // get elapsed time (in seconds) between previous and current frames
     static double prev_time = glfwGetTime();
     double curr_time = glfwGetTime();
     delta_time = curr_time - prev_time;
     prev_time = curr_time;
     // fps calculations
     static double count = 0.0; // number of game loop iterations
     static double start_time = glfwGetTime();
     // get elapsed time since very beginning (in seconds) ...
     double elapsed_time = curr_time - start_time;
     if (fps_control) {
         // sleep for the remaining time if frame was rendered too fast
         std::this_thread::sleep_for(std::chrono::milliseconds((int)((time_per_frame-delta_time) * 1000)));
     }
     ++count;
     // update fps at least every 10 seconds ...
     fps_calc_interval = (fps_calc_interval < 0.0) ? 0.0 : fps_calc_interval;
     fps_calc_interval = (fps_calc_interval > 10.0) ? 10.0 : fps_calc_interval;
     if (elapsed_time > fps_calc_interval) {
         GLWindow::fps = count / elapsed_time;
         start_time = curr_time;
         count = 0.0;
     }
 }
References delta_time, fps, fps_control, and time_per_frame.
Referenced by Update().
Member Data Documentation
delta_time
GLdouble GLWindow::delta_time static
Definition at line 49 of file GLWindow.h.
Referenced by update_time().
fps
GLdouble GLWindow::fps static
Definition at line 48 of file GLWindow.h.
Referenced by GLApp::Update(), and update_time().
height
GLint GLWindow::height static
Definition at line 47 of file GLWindow.h.
Referenced by GLApp::GLObject::draw(), GLWindow(), GLApp::init_scene(), GLApp::Initialize(), and Initialize().
ptr_window
GLFWwindow * GLWindow::ptr_window static
Definition at line 51 of file GLWindow.h.
Referenced by Initialize(), and GLApp::Update().
title
std::string GLWindow::title static
Definition at line 50 of file GLWindow.h.
Referenced by GLWindow(), Initialize(), and GLApp::Update().
width
GLint GLWindow::width static
Definition at line 47 of file GLWindow.h.
Referenced by GLApp::GLObject::draw(), GLWindow(), GLApp::init_scene(), GLApp::Initialize(), and Initialize().
The documentation for this class was generated from the following files:
include/Graphic_gl/GLWindow.h
src/graphic_gl/GLWindow.cpp