CSD2126: GLSLShader Class Reference
GLSLShader Class Reference
#include <glslshader.h>
Public Member Functions
GLSLShader ()
GLboolean CompileLinkValidate (std::vector< std::pair< GLenum, std::string >>)
GLboolean CompileShaderFromFile (GLenum shader_type, std::string const &file_name)
GLboolean CompileShaderFromString (GLenum shader_type, std::string const &shader_src)
GLboolean Link ()
void Use ()
void UnUse ()
GLboolean Validate ()
GLuint GetHandle () const
GLboolean IsLinked () const
std::string GetLog () const
void BindAttribLocation (GLuint index, GLchar const *name)
void BindFragDataLocation (GLuint color_number, GLchar const *name)
void DeleteShaderProgram ()
void SetUniform (GLchar const *name, GLboolean val)
void SetUniform (GLchar const *name, GLint val)
void SetUniform (GLchar const *name, GLfloat val)
void SetUniform (GLchar const *name, GLfloat x, GLfloat y)
void SetUniform (GLchar const *name, GLfloat x, GLfloat y, GLfloat z)
void SetUniform (GLchar const *name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
void SetUniform (GLchar const *name, glm::vec2 const &val)
void SetUniform (GLchar const *name, glm::vec3 const &val)
void SetUniform (GLchar const *name, glm::vec4 const &val)
void SetUniform (GLchar const *name, glm::mat3 const &val)
void SetUniform (GLchar const *name, glm::mat4 const &val)
void PrintActiveAttribs () const
void PrintActiveUniforms () const
Private Types
enum ShaderType {
VERTEX_SHADER = GL_VERTEX_SHADER , FRAGMENT_SHADER = GL_FRAGMENT_SHADER , GEOMETRY_SHADER = GL_GEOMETRY_SHADER , TESS_CONTROL_SHADER = GL_TESS_CONTROL_SHADER ,
TESS_EVALUATION_SHADER = GL_TESS_EVALUATION_SHADER
}
Private Member Functions
GLint GetUniformLocation (GLchar const *name)
GLboolean FileExists (std::string const &file_name)
Private Attributes
GLuint pgm_handle = 0
GLboolean is_linked = GL_FALSE
std::string log_string
Detailed Description
GLSLShader class.
Definition at line 39 of file glslshader.h.
Member Enumeration Documentation
ShaderType
enum GLSLShader::ShaderType private
Enumerator
VERTEX_SHADER
FRAGMENT_SHADER
GEOMETRY_SHADER
TESS_CONTROL_SHADER
TESS_EVALUATION_SHADER
Definition at line 162 of file glslshader.h.
                   {
     VERTEX_SHADER = GL_VERTEX_SHADER,
     FRAGMENT_SHADER = GL_FRAGMENT_SHADER,
     GEOMETRY_SHADER = GL_GEOMETRY_SHADER,
     TESS_CONTROL_SHADER = GL_TESS_CONTROL_SHADER,
     TESS_EVALUATION_SHADER = GL_TESS_EVALUATION_SHADER,
     // ignore compute shader for now because it is not connected to
     // the graphics pipe
     // COMPUTE_SHADER = GL_COMPUTE_SHADER
   };
Constructor & Destructor Documentation
GLSLShader()
GLSLShader::GLSLShader () inline
Definition at line 46 of file glslshader.h.
                : pgm_handle(0), is_linked(GL_FALSE) {
   }
Member Function Documentation
BindAttribLocation()
void GLSLShader::BindAttribLocation (GLuint index, GLchar const * name)
Definition at line 208 of file glslshader.cpp.
{
   glBindAttribLocation(pgm_handle, index, name);
 }
References pgm_handle.
BindFragDataLocation()
void GLSLShader::BindFragDataLocation (GLuint color_number, GLchar const * name)
Definition at line 212 of file glslshader.cpp.
{
   glBindFragDataLocation(pgm_handle, color_number, name);
 }
References pgm_handle.
CompileLinkValidate()
GLboolean GLSLShader::CompileLinkValidate (std::vector< std::pair< GLenum, std::string >> vec)
Definition at line 35 of file glslshader.cpp.
{
   for (auto& elem : vec) {
     if (GL_FALSE == CompileShaderFromFile(elem.first, elem.second.c_str())) {
       return GL_FALSE;
     }
   }
   if (GL_FALSE == Link()) {
     return GL_FALSE;
   }
   if (GL_FALSE == Validate()) {
     return GL_FALSE;
   }
   PrintActiveAttribs();
   PrintActiveUniforms();
   return GL_TRUE;
 }
References CompileShaderFromFile(), Link(), PrintActiveAttribs(), PrintActiveUniforms(), and Validate().
Referenced by GLApp::insert_shdrpgm().
CompileShaderFromFile()
GLboolean GLSLShader::CompileShaderFromFile (GLenum shader_type, std::string const & file_name)
Definition at line 54 of file glslshader.cpp.
{
   if (GL_FALSE == FileExists(file_name)) {
     log_string = "File not found";
     return GL_FALSE;
   }
   if (pgm_handle <= 0) {
     pgm_handle = glCreateProgram();
     if (0 == pgm_handle) {
       log_string = "Cannot create program handle";
       return GL_FALSE;
     }
   }
   std::ifstream shader_file(file_name, std::ifstream::in);
   if (!shader_file) {
     log_string = "Error opening file " + file_name;
     return GL_FALSE;
   }
   std::stringstream buffer;
   buffer << shader_file.rdbuf();
   shader_file.close();
   return CompileShaderFromString(shader_type, buffer.str());
 }
References CompileShaderFromString(), FileExists(), log_string, and pgm_handle.
Referenced by CompileLinkValidate().
CompileShaderFromString()
GLboolean GLSLShader::CompileShaderFromString (GLenum shader_type, std::string const & shader_src)
Definition at line 79 of file glslshader.cpp.
{
   if (pgm_handle <= 0) {
     pgm_handle = glCreateProgram();
     if (0 == pgm_handle) {
       log_string = "Cannot create program handle";
       return GL_FALSE;
     }
   }
   GLuint shader_handle = 0;
   switch (shader_type) {
   case VERTEX_SHADER: shader_handle = glCreateShader(GL_VERTEX_SHADER); break;
   case FRAGMENT_SHADER: shader_handle = glCreateShader(GL_FRAGMENT_SHADER); break;
   case GEOMETRY_SHADER: shader_handle = glCreateShader(GL_GEOMETRY_SHADER); break;
   case TESS_CONTROL_SHADER: shader_handle = glCreateShader(GL_TESS_CONTROL_SHADER); break;
   case TESS_EVALUATION_SHADER: shader_handle = glCreateShader(GL_TESS_EVALUATION_SHADER); break;
   //case COMPUTE_SHADER: shader_handle = glCreateShader(GL_COMPUTE_SHADER); break;
   default:
     log_string = "Incorrect shader type";
     return GL_FALSE;
   }
   // load shader source code into shader object
   GLchar const* shader_code[] = { shader_src.c_str() };
   glShaderSource(shader_handle, 1, shader_code, NULL);
   // compile the shader
   glCompileShader(shader_handle);
   // check compilation status
   GLint comp_result;
   glGetShaderiv(shader_handle, GL_COMPILE_STATUS, &comp_result);
   if (GL_FALSE == comp_result) {
     log_string = "Vertex shader compilation failed\n";
     GLint log_len;
     glGetShaderiv(shader_handle, GL_INFO_LOG_LENGTH, &log_len);
     if (log_len > 0) {
       GLchar *log = new GLchar[log_len];
       GLsizei written_log_len;
       glGetShaderInfoLog(shader_handle, log_len, &written_log_len, log);
       log_string += log;
       delete[] log;
     }
     return GL_FALSE;
   }
   else { // attach the shader to the program object
     glAttachShader(pgm_handle, shader_handle);
     return GL_TRUE;
   }
 }
References FRAGMENT_SHADER, GEOMETRY_SHADER, log_string, pgm_handle, TESS_CONTROL_SHADER, TESS_EVALUATION_SHADER, and VERTEX_SHADER.
Referenced by CompileShaderFromFile().
DeleteShaderProgram()
void GLSLShader::DeleteShaderProgram ()
Definition at line 28 of file glslshader.cpp.
{
   if (pgm_handle > 0) {
     glDeleteProgram(pgm_handle);
   }
 }
References pgm_handle.
FileExists()
GLboolean GLSLShader::FileExists (std::string const & file_name) private
Definition at line 23 of file glslshader.cpp.
{
   std::ifstream infile(file_name); return infile.good();
 }
Referenced by CompileShaderFromFile().
GetHandle()
GLuint GLSLShader::GetHandle () const
Definition at line 196 of file glslshader.cpp.
{
   return pgm_handle;
 }
References pgm_handle.
GetLog()
std::string GLSLShader::GetLog () const
Definition at line 204 of file glslshader.cpp.
{
   return log_string;
 }
References log_string.
Referenced by GLApp::insert_shdrpgm().
GetUniformLocation()
GLint GLSLShader::GetUniformLocation (GLchar const * name) private
Definition at line 18 of file glslshader.cpp.
{
   return glGetUniformLocation(pgm_handle, name);
 }
References pgm_handle.
IsLinked()
GLboolean GLSLShader::IsLinked () const
Definition at line 200 of file glslshader.cpp.
{
   return is_linked;
 }
References is_linked.
Referenced by GLApp::insert_shdrpgm().
Link()
GLboolean GLSLShader::Link ()
Definition at line 131 of file glslshader.cpp.
{
   if (GL_TRUE == is_linked) {
     return GL_TRUE;
   }
   if (pgm_handle <= 0) {
     return GL_FALSE;
   }
   glLinkProgram(pgm_handle); // link the various compiled shaders
   // verify the link status
   GLint lnk_status;
   glGetProgramiv(pgm_handle, GL_LINK_STATUS, &lnk_status);
   if (GL_FALSE == lnk_status) {
     log_string = "Failed to link shader program\n";
     GLint log_len;
     glGetProgramiv(pgm_handle, GL_INFO_LOG_LENGTH, &log_len);
     if (log_len > 0) {
       GLchar *log_str = new GLchar[log_len];
       GLsizei written_log_len;
       glGetProgramInfoLog(pgm_handle, log_len, &written_log_len, log_str);
       log_string += log_str;
       delete[] log_str;
     }
     return GL_FALSE;
   }
   return is_linked = GL_TRUE;
 }
References is_linked, log_string, and pgm_handle.
Referenced by CompileLinkValidate().
PrintActiveAttribs()
void GLSLShader::PrintActiveAttribs () const
Definition at line 325 of file glslshader.cpp.
{
 #if 1
   GLint max_length, num_attribs;
   glGetProgramiv(pgm_handle, GL_ACTIVE_ATTRIBUTE_MAX_LENGTH, &max_length);
   glGetProgramiv(pgm_handle, GL_ACTIVE_ATTRIBUTES, &num_attribs);
   GLchar *pname = new GLchar[max_length];
   std::cout << "Index\t|\tName\n";
   std::cout << "----------------------------------------------------------------------\n";
   for (GLint i = 0; i < num_attribs; ++i) {
     GLsizei written;
     GLint size;
     GLenum type;
     glGetActiveAttrib(pgm_handle, i, max_length, &written, &size, &type, pname);
     GLint loc = glGetAttribLocation(pgm_handle, pname);
     std::cout << loc << "\t\t" << pname << std::endl;
   }
   std::cout << "----------------------------------------------------------------------\n";
   delete[] pname;
 #else
   GLint numAttribs;
   glGetProgramInterfaceiv(pgm_handle, GL_PROGRAM_INPUT, GL_ACTIVE_RESOURCES, &numAttribs);
   GLenum properties[] = { GL_NAME_LENGTH, GL_TYPE, GL_LOCATION };
   std::cout << "Active attributes:" << std::endl;
   for (GLint i = 0; i < numAttribs; ++i) {
     GLint results[3];
     glGetProgramResourceiv(pgm_handle, GL_PROGRAM_INPUT, i, 3, properties, 3, NULL, results);
     GLint nameBufSize = results[0] + 1;
     GLchar *pname = new GLchar[nameBufSize];
     glGetProgramResourceName(pgm_handle, GL_PROGRAM_INPUT, i, nameBufSize, NULL, pname);
     //   std::cout << results[2] << " " << pname << " " << getTypeString(results[1]) << std::endl;
     std::cout << results[2] << " " << pname << " " << results[1] << std::endl;
     delete[] pname;
   }
 #endif
 }
References pgm_handle.
Referenced by CompileLinkValidate().
PrintActiveUniforms()
void GLSLShader::PrintActiveUniforms () const
Definition at line 363 of file glslshader.cpp.
{
   GLint max_length;
   glGetProgramiv(pgm_handle, GL_ACTIVE_UNIFORM_MAX_LENGTH, &max_length);
   GLchar *pname = new GLchar[max_length];
   GLint num_uniforms;
   glGetProgramiv(pgm_handle, GL_ACTIVE_UNIFORMS, &num_uniforms);
   std::cout << "Location\t|\tName\n";
   std::cout << "----------------------------------------------------------------------\n";
   for (GLint i = 0; i < num_uniforms; ++i) {
     GLsizei written;
     GLint size;
     GLenum type;
     glGetActiveUniform(pgm_handle, i, max_length, &written, &size, &type, pname);
     GLint loc = glGetUniformLocation(pgm_handle, pname);
     std::cout << loc << "\t\t" << pname << std::endl;
   }
   std::cout << "----------------------------------------------------------------------\n";
   delete[] pname;
 }
References pgm_handle.
Referenced by CompileLinkValidate().
SetUniform() [1/11]
void GLSLShader::SetUniform (GLchar const * name, GLboolean val)
Definition at line 216 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform1i(loc, val);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [2/11]
void GLSLShader::SetUniform (GLchar const * name, GLfloat val)
Definition at line 236 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform1f(loc, val);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [3/11]
void GLSLShader::SetUniform (GLchar const * name, GLfloat x, GLfloat y)
Definition at line 246 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform2f(loc, x, y);
   } else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [4/11]
void GLSLShader::SetUniform (GLchar const * name, GLfloat x, GLfloat y, GLfloat z)
Definition at line 255 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform3f(loc, x, y, z);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [5/11]
void GLSLShader::SetUniform (GLchar const * name, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Definition at line 266 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform4f(loc, x, y, z, w);
   } else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle, and w.
SetUniform() [6/11]
void GLSLShader::SetUniform (GLchar const * name, GLint val)
Definition at line 226 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform1i(loc, val);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [7/11]
void GLSLShader::SetUniform (GLchar const * name, glm::mat3 const & val)
Definition at line 305 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniformMatrix3fv(loc, 1, GL_FALSE, &val[0][0]);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [8/11]
void GLSLShader::SetUniform (GLchar const * name, glm::mat4 const & val)
Definition at line 315 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniformMatrix4fv(loc, 1, GL_FALSE, &val[0][0]);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [9/11]
void GLSLShader::SetUniform (GLchar const * name, glm::vec2 const & val)
Definition at line 275 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform2f(loc, val.x, val.y);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [10/11]
void GLSLShader::SetUniform (GLchar const * name, glm::vec3 const & val)
Definition at line 285 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform3f(loc, val.x, val.y, val.z);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
SetUniform() [11/11]
void GLSLShader::SetUniform (GLchar const * name, glm::vec4 const & val)
Definition at line 295 of file glslshader.cpp.
{
   GLint loc = glGetUniformLocation(pgm_handle, name);
   if (loc >= 0) {
     glUniform4f(loc, val.x, val.y, val.z, val.w);
   }
   else {
     std::cout << "Uniform variable " << name << " doesn't exist" << std::endl;
   }
 }
References pgm_handle.
UnUse()
void GLSLShader::UnUse ()
Definition at line 166 of file glslshader.cpp.
{
   glUseProgram(0);
 }
Use()
void GLSLShader::Use ()
Definition at line 160 of file glslshader.cpp.
                      {
   if (pgm_handle > 0 && is_linked == GL_TRUE) {
     glUseProgram(pgm_handle);
   }
 }
References is_linked, and pgm_handle.
Validate()
GLboolean GLSLShader::Validate ()
Definition at line 170 of file glslshader.cpp.
{
   if (pgm_handle <= 0 || is_linked == GL_FALSE) {
     return GL_FALSE;
   }
   glValidateProgram(pgm_handle);
   GLint status;
   glGetProgramiv(pgm_handle, GL_VALIDATE_STATUS, &status);
   if (GL_FALSE == status) {
     log_string = "Failed to validate shader program for current OpenGL context\n";
     GLint log_len;
     glGetProgramiv(pgm_handle, GL_INFO_LOG_LENGTH, &log_len);
     if (log_len > 0) {
       GLchar *log_str = new GLchar[log_len];
       GLsizei written_log_len;
       glGetProgramInfoLog(pgm_handle, log_len, &written_log_len, log_str);
       log_string += log_str;
       delete[] log_str;
     }
     return GL_FALSE;
   }
   else {
     return GL_TRUE;
   }
 }
References is_linked, log_string, and pgm_handle.
Referenced by CompileLinkValidate().
Member Data Documentation
is_linked
GLboolean GLSLShader::is_linked = GL_FALSE private
Definition at line 174 of file glslshader.h.
Referenced by IsLinked(), Link(), Use(), and Validate().
log_string
std::string GLSLShader::log_string private
Definition at line 175 of file glslshader.h.
Referenced by CompileShaderFromFile(), CompileShaderFromString(), GetLog(), Link(), and Validate().
pgm_handle
GLuint GLSLShader::pgm_handle = 0 private
Definition at line 173 of file glslshader.h.
Referenced by BindAttribLocation(), BindFragDataLocation(), CompileShaderFromFile(), CompileShaderFromString(), DeleteShaderProgram(), GetHandle(), GetUniformLocation(), Link(), PrintActiveAttribs(), PrintActiveUniforms(), SetUniform(), Use(), and Validate().
The documentation for this class was generated from the following files:
include/Graphic_gl/glslshader.h
src/graphic_gl/glslshader.cpp