CSD2126: CoreEngine Class Reference
CoreEngine Class Reference
#include <Core_Engine.h>
Public Member Functions
CoreEngine ()
~CoreEngine ()
void GameLoop ()
void AddSystem (ISystems *sys)
void DestroySystem ()
void Initialize ()
Private Attributes
std::vector< ISystems * > Systems
unsigned last_update
bool game_active
Detailed Description
Definition at line 8 of file Core_Engine.h.
Constructor & Destructor Documentation
CoreEngine()
CoreEngine::CoreEngine ()
Definition at line 6 of file Core_Engine.cpp.
{
   last_update = 0;
   game_active = true;
   CORE = this;
 }
References CORE, game_active, and last_update.
~CoreEngine()
CoreEngine::~CoreEngine ()
Definition at line 12 of file Core_Engine.cpp.
 {}
Member Function Documentation
AddSystem()
void CoreEngine::AddSystem (ISystems * sys)
Definition at line 32 of file Core_Engine.cpp.
{
   Systems.push_back(sys);
 }
References Systems.
Referenced by main().
DestroySystem()
void CoreEngine::DestroySystem ()
Definition at line 36 of file Core_Engine.cpp.
{
   for (unsigned i = 0; i < Systems.size(); ++i)
   {
     delete Systems[Systems.size() - i - 1];
   }
 }
References Systems.
Referenced by main().
GameLoop()
void CoreEngine::GameLoop ()
Definition at line 14 of file Core_Engine.cpp.
{
   //Get the current time from chrono in milliseconds
   auto now = std::chrono::system_clock::now();
   auto duration = now.time_since_epoch();
   unsigned current_time = std::chrono::duration_cast<std::chrono::milliseconds>(duration).count();
   //Convert it to the time passed since the last frame (in seconds)
   float dt = (current_time - last_update) / 1000.0f;
   //Update the when the last update started
   last_update = current_time;
   while (game_active) {
     for (int i = 0; i < Systems.size(); i++) {
       Systems[i]->Update(dt);
     }
   }
 }
References game_active, last_update, and Systems.
Referenced by main().
Initialize()
void CoreEngine::Initialize ()
Definition at line 43 of file Core_Engine.cpp.
{
   for (unsigned i = 0; i < Systems.size(); ++i)
     Systems[i]->Initialize();
 }
References Systems.
Referenced by main().
Member Data Documentation
game_active
bool CoreEngine::game_active private
Definition at line 22 of file Core_Engine.h.
Referenced by CoreEngine(), and GameLoop().
last_update
unsigned CoreEngine::last_update private
Definition at line 21 of file Core_Engine.h.
Referenced by CoreEngine(), and GameLoop().
Systems
std::vector<ISystems*> CoreEngine::Systems private
Definition at line 20 of file Core_Engine.h.
Referenced by AddSystem(), DestroySystem(), GameLoop(), and Initialize().
The documentation for this class was generated from the following files:
include/Core_Engine.h
src/Core_Engine.cpp