CSD2126: TextSerialization Class Reference
TextSerialization Class Reference
#include <text_serialization.h>
Public Member Functions
virtual bool openFileRead (const std::string &file)
virtual bool openFileWrite (const std::string &file)
virtual bool closeFile ()
virtual bool isGood ()
virtual void readInt (int &i)
virtual void readFloat (int &f)
virtual void readString (std::string &str)
virtual void writeInt (int &i)
virtual void writeFloat (int &f)
virtual void writeString (std::string &str)
Public Attributes
std::fstream stream
Detailed Description
Definition at line 6 of file text_serialization.h.
Member Function Documentation
closeFile()
bool TextSerialization::closeFile () virtual
Implements Serialization.
Definition at line 15 of file text_serialization.cpp.
 {
   stream.close();
   return !stream.is_open();
 }
References stream.
Referenced by s_importMapFromFile().
isGood()
bool TextSerialization::isGood () virtual
Implements Serialization.
Definition at line 21 of file text_serialization.cpp.
 {
   return stream.good();
 }
References stream.
Referenced by GameObjectFactory::buildFromFile(), and s_importMapFromFile().
openFileRead()
bool TextSerialization::openFileRead (const std::string & file) virtual
Implements Serialization.
Definition at line 3 of file text_serialization.cpp.
 {
   stream.open(file.c_str(), std::ios::in);
   return stream.is_open();
 }
References stream.
Referenced by GameObjectFactory::buildFromFile(), and s_importMapFromFile().
openFileWrite()
bool TextSerialization::openFileWrite (const std::string & file) virtual
Implements Serialization.
Definition at line 9 of file text_serialization.cpp.
 {
   stream.open(file.c_str(), std::ios::out | std::ios::trunc);
   return stream.is_open();
 }
References stream.
readFloat()
void TextSerialization::readFloat (int & f) virtual
Implements Serialization.
Definition at line 31 of file text_serialization.cpp.
 {
   stream >> f;
 }
References stream.
readInt()
void TextSerialization::readInt (int & i) virtual
Implements Serialization.
Definition at line 26 of file text_serialization.cpp.
 {
   stream >> i;
 }
References stream.
Referenced by s_importMapFromFile().
readString()
void TextSerialization::readString (std::string & str) virtual
Implements Serialization.
Definition at line 36 of file text_serialization.cpp.
 {
   stream >> str;
 }
References stream.
Referenced by GameObjectFactory::buildFromFile().
writeFloat()
void TextSerialization::writeFloat (int & f) virtual
Implements Serialization.
Definition at line 46 of file text_serialization.cpp.
 {
   stream << f;
 }
References stream.
writeInt()
void TextSerialization::writeInt (int & i) virtual
Implements Serialization.
Definition at line 41 of file text_serialization.cpp.
 {
   stream << i;
 }
References stream.
writeString()
void TextSerialization::writeString (std::string & str) virtual
Implements Serialization.
Definition at line 51 of file text_serialization.cpp.
 {
   stream << str;
 }
References stream.
Member Data Documentation
stream
std::fstream TextSerialization::stream
Definition at line 10 of file text_serialization.h.
Referenced by closeFile(), isGood(), openFileRead(), openFileWrite(), readFloat(), readInt(), readString(), writeFloat(), writeInt(), and writeString().
The documentation for this class was generated from the following files:
src/Assets Manager/text_serialization.h
src/Assets Manager/text_serialization.cpp