CSD2126: GameObjectFactory Class Reference
GameObjectFactory Class Reference
#include <Factory.h>
Public Member Functions
GameObjectFactory ()
~GameObjectFactory ()
GOC * createGameObj (std::string gameObjType)
void destroyGameObj (GOC *gameObject)
virtual void Update (float time)
std::string GetName ()
void destroyAllGameObjs ()
GOC * createEmptyGameObj ()
GOC * buildFromFile (const std::string &filename)
void idGameObj (GOC *gameObj)
GOC * getObjWithID (GOCId id)
void AddComponentCreator (const std::string &name, ComponentCreator *creator)
Public Member Functions inherited from ISystems
virtual void Initialize ()
virtual void Free ()
virtual void GetSystemName ()
Private Types
typedef std::map< std::string, ComponentCreator * > componentCreatorMap
typedef std::map< unsigned, GOC * > gameObjIDMap
Private Attributes
unsigned lastGameObjID
componentCreatorMap componentMap
gameObjIDMap gameObjectMap
std::set< GOC * > gameObjsToBeDeleted
Friends
class Physics
Detailed Description
Definition at line 14 of file Factory.h.
Member Typedef Documentation
componentCreatorMap
typedef std::map< std::string, ComponentCreator*> GameObjectFactory::componentCreatorMap private
Definition at line 48 of file Factory.h.
gameObjIDMap
typedef std::map<unsigned, GOC*> GameObjectFactory::gameObjIDMap private
Definition at line 51 of file Factory.h.
Constructor & Destructor Documentation
GameObjectFactory()
GameObjectFactory::GameObjectFactory ()
Definition at line 6 of file Factory.cpp.
 {
   gameObjFactory = this;
   lastGameObjID = 0;
 }
References gameObjFactory, and lastGameObjID.
~GameObjectFactory()
GameObjectFactory::~GameObjectFactory ()
Definition at line 12 of file Factory.cpp.
 {
   componentCreatorMap::iterator it = componentMap.begin();
   for  (; it != componentMap.end(); ++it)
   {
     delete it->second;
   }
 }
References componentMap.
Member Function Documentation
AddComponentCreator()
void GameObjectFactory::AddComponentCreator (const std::string & name, ComponentCreator * creator)
Definition at line 118 of file Factory.cpp.
 {
   componentMap[name] = creator;
 }
References componentMap.
Referenced by GameLogic::Initialize().
buildFromFile()
GOC * GameObjectFactory::buildFromFile (const std::string & filename)
Definition at line 67 of file Factory.cpp.
 {
   TextSerialization textStream;
   textStream.openFileRead(filename);
   if (textStream.isGood())
   {
     GOC* gameObj = new GOC();
     std::string componentName;
     while (textStream.isGood())
     {
       textStream.readString(componentName);
       componentCreatorMap::iterator it = componentMap.find(componentName);
       if (it != componentMap.end())
       {
         ComponentCreator* creator = it->second;
         GameComponent* component = creator->Create();
         gameObj->AddComponent(creator->typeId, component);
       }
     }
     idGameObj(gameObj);
     return gameObj;
   }
   return NULL;
 }
References GameObjectComposition::AddComponent(), componentMap, ComponentCreator::Create(), idGameObj(), TextSerialization::isGood(), TextSerialization::openFileRead(), TextSerialization::readString(), and ComponentCreator::typeId.
createEmptyGameObj()
GOC * GameObjectFactory::createEmptyGameObj ()
Definition at line 60 of file Factory.cpp.
 {
   GOC* gameObj = new GOC();
   idGameObj(gameObj);
   return gameObj;
 }
References idGameObj().
createGameObj()
GOC * GameObjectFactory::createGameObj (std::string gameObjType)
Definition at line 21 of file Factory.cpp.
 {
   GOC* newGameObj = NULL;
   return newGameObj;
 }
destroyAllGameObjs()
void GameObjectFactory::destroyAllGameObjs ()
Definition at line 49 of file Factory.cpp.
 {
   gameObjIDMap::iterator it = gameObjectMap.begin();
   for (; it != gameObjectMap.end(); ++it)
   {
     delete it->second;
   }
   gameObjectMap.clear();
 }
References gameObjectMap.
destroyGameObj()
void GameObjectFactory::destroyGameObj (GOC * gameObject)
Definition at line 28 of file Factory.cpp.
 {
   gameObjsToBeDeleted.insert(gameObject);
 }
References gameObjsToBeDeleted.
GetName()
std::string GameObjectFactory::GetName () inline
Definition at line 26 of file Factory.h.
 { return "Factory"; };
getObjWithID()
GOC * GameObjectFactory::getObjWithID (GOCId id)
Definition at line 105 of file Factory.cpp.
 {
   gameObjIDMap::iterator it = gameObjectMap.find(id);
   if (it != gameObjectMap.end())
   {
     return it->second;
   }
   else
   {
     return NULL;
   }
 }
References gameObjectMap.
idGameObj()
void GameObjectFactory::idGameObj (GOC * gameObj)
Definition at line 98 of file Factory.cpp.
 {
   ++lastGameObjID;
   gameObj->ObjectId = lastGameObjID;
   gameObjectMap[lastGameObjID] = gameObj;
 }
References gameObjectMap, lastGameObjID, and GameObjectComposition::ObjectId.
Referenced by buildFromFile(), and createEmptyGameObj().
Update()
void GameObjectFactory::Update (float time) virtual
Implements ISystems.
Definition at line 32 of file Factory.cpp.
{
   std::set<GOC*>::iterator it = gameObjsToBeDeleted.begin();
   for (; it != gameObjsToBeDeleted.end(); ++it)
   {
     GOC* gameObject = *it;
     gameObjIDMap::iterator idItr = gameObjectMap.find(gameObject->ObjectId);
     //ErrorIf(idItr == gameObjectMap.end(), "Object %d was double deleted or is bad memory.", gameObject->ObjectId);
     if (idItr != gameObjectMap.end())
     {
       //Delete it and remove its entry in the Id map
       delete gameObject;
       gameObjectMap.erase(idItr);
     }
   }
   //All objects to be delete have been deleted
   gameObjsToBeDeleted.clear();
 }
References gameObjectMap, gameObjsToBeDeleted, and GameObjectComposition::ObjectId.
Friends And Related Function Documentation
Physics
friend class Physics friend
Definition at line 42 of file Factory.h.
Member Data Documentation
componentMap
componentCreatorMap GameObjectFactory::componentMap private
Definition at line 49 of file Factory.h.
Referenced by AddComponentCreator(), buildFromFile(), and ~GameObjectFactory().
gameObjectMap
gameObjIDMap GameObjectFactory::gameObjectMap private
Definition at line 52 of file Factory.h.
Referenced by destroyAllGameObjs(), getObjWithID(), idGameObj(), Update(), and Physics::Update().
gameObjsToBeDeleted
std::set<GOC*> GameObjectFactory::gameObjsToBeDeleted private
Definition at line 54 of file Factory.h.
Referenced by destroyGameObj(), and Update().
lastGameObjID
unsigned GameObjectFactory::lastGameObjID private
Definition at line 44 of file Factory.h.
Referenced by GameObjectFactory(), and idGameObj().
The documentation for this class was generated from the following files:
include/Factory.h
src/Factory.cpp