CSD2126: src/Assets Manager/file_reader.cpp File Reference
file_reader.cpp File Reference
#include "file_reader.h"
#include "text_serialization.h"
#include <iostream>
#include <vector>
Functions
bool importMapFromFile (char *textfile)
bool s_importMapFromFile (std::string textfile)
Function Documentation
importMapFromFile()
bool importMapFromFile (char * textfile)
Definition at line 12 of file file_reader.cpp.
 {
   mapdata.clear();
   std::ifstream mapfile;
   mapfile.open(textfile, std::ios::in);
   if (!mapfile.is_open())
   {
     std::cout << "Error opening map file." << std::endl;
     return false;
   }
   int mapwidth{};
   int mapheight{};
   int checker{};
   while (!mapfile.eof())
   {
     char id{};
     mapfile.get(id);
     if (checker == 0 && id >= '0' && id <= '9')
     {
       mapwidth = static_cast<int>(id - '0');
       mapfile.get(id);
       while (id >= '0' && id <= '9')
       {
         mapwidth = mapwidth * 10 + static_cast<int>(id - '0');
         mapfile.get(id);
       }
       checker++;
       continue;
     }
     if (checker == 1 && id >= '0' && id <= '9')
     {
       mapheight = static_cast<int>(id - '0');
       mapfile.get(id);
       while (id >= '0' && id <= '9')
       {
         mapheight = mapheight * 10 + static_cast<int>(id - '0');
         mapfile.get(id);
       }
       checker++;
       if (!(mapheight > 0 && mapwidth > 0))
       {
         std::cout << "Invalid map format: width and height must be > 0." << std::endl;
         return false;
       }
       continue;
     }
     if (checker > 1)
     {
       for (int i{}; i < mapwidth; i++)
       {
         int data{};
         std::vector<int> row;
         for (int j{}; j < mapheight; j++)
         {
           while (mapfile.get(id)) // Cycle till int found
           {
             data = static_cast<int>(id - '0');
             mapfile.get(id);
             while (id >= '0' && id <= '9') // Check consecutive int
             {
               data = data * 10 + static_cast<int>(id - '0');
               mapfile.get(id);
             }
             break;
           }
           if (mapfile.eof()) // Possible cause of error if directly before eof, the character is an interger and map dimension matches, text file could add a END at the end if this is a problem
           {
             std::cout << "Dimension Mismatch: width or height in the file did not match." << std::endl;
             mapdata.clear();
             return false;
           }
           row.push_back(data);
         }
         mapdata.push_back(row);
       }
     }
   }
   mapfile.close();
   return true;
 }
References mapdata.
s_importMapFromFile()
bool s_importMapFromFile (std::string textfile)
Definition at line 104 of file file_reader.cpp.
 {
   mapdata.clear();
   TextSerialization stream;
   bool fileopened = stream.openFileRead(textfile);
   if (!fileopened)
   {
     std::cout << "Error opening map file." << std::endl;
     return false;
   }
   int mapwidth{};
   int mapheight{};
   if (stream.isGood())
   {
     int id{};
     stream.readInt(id);
     mapwidth = id;
     stream.readInt(id);
     mapheight = id;
     if (!(mapheight > 0 && mapwidth > 0))
     {
       std::cout << "Invalid map format: width and height must be > 0." << std::endl;
       return false;
     }
     for (int i{}; i < mapheight; i++)
     {
       int data{};
       std::vector<int> row;
       for (int j{}; j < mapwidth; j++)
       {
         if (stream.isGood())
         {
           stream.readInt(id);
           data = id;
         }
         else if (!stream.isGood()) // Possible cause of error if directly before eof, the character is an interger and map dimension matches, text file could add a END at the end if this is a problem
         {
           // Not sure if the error exist while using serialization method of reading
           std::cout << "Dimension Mismatch: width or height in the file did not match." << std::endl;
           mapdata.clear();
           return false;
         }
         row.push_back(data);
       }
       mapdata.push_back(row);
     }
   }
   else
   {
     stream.closeFile();
     return false;
   }
   stream.closeFile();
   return true;
 }
References TextSerialization::closeFile(), TextSerialization::isGood(), mapdata, TextSerialization::openFileRead(), and TextSerialization::readInt().