CSD2126: src/input.cpp File Reference
input.cpp File Reference
#include "input.h"
Functions
int at (KEY index)
void KeyCallBack (GLFWwindow *pWin, int key, int scancode, int action, int mod)
void MouseButtonCallBack (GLFWwindow *pWin, int button, int action, int mod)
void MousePosCallBack (GLFWwindow *pWin, double xpos, double ypos)
bool IsReleased (KEY key)
Function Documentation
at()
int at (KEY index)
Definition at line 64 of file input.cpp.
 {
   return static_cast<int>(index);
 }
Referenced by input::IsPressed(), input::IsPressedRepeatedly(), IsReleased(), KeyCallBack(), and MouseButtonCallBack().
IsReleased()
bool IsReleased (KEY key)
Definition at line 135 of file input.cpp.
 {
   return buttons[at(key)].IsReleased();
 }
References at().
KeyCallBack()
void KeyCallBack (GLFWwindow * pWin, int key, int scancode, int action, int mod)
Definition at line 69 of file input.cpp.
 {
   switch (key)
   {
   case GLFW_KEY_W:
   {
     buttons[at(KEY::w)].SetKeyState(action);
   }
   break;
   case GLFW_KEY_A:
   {
     buttons[at(KEY::a)].SetKeyState(action);
   }
   break;
   case GLFW_KEY_S:
   {
     buttons[at(KEY::s)].SetKeyState(action);
   }
   break;
   case GLFW_KEY_D:
   {
     buttons[at(KEY::d)].SetKeyState(action);
   }
   }
   if (GLFW_KEY_ESCAPE == key && GLFW_PRESS == action)
   {
     glfwSetWindowShouldClose(pWin, GLFW_TRUE);
   }
 }
References a, at(), d, s, and w.
Referenced by input::Init().
MouseButtonCallBack()
void MouseButtonCallBack (GLFWwindow * pWin, int button, int action, int mod)
Definition at line 99 of file input.cpp.
 {
   switch (button)
   {
   case GLFW_MOUSE_BUTTON_1:
   {
     buttons[at(KEY::mouseL)].SetKeyState(action);
   }
   break;
   case GLFW_MOUSE_BUTTON_2:
   {
     buttons[at(KEY::mouseR)].SetKeyState(action);
   }
   }
 }
References at(), mouseL, and mouseR.
Referenced by input::Init().
MousePosCallBack()
void MousePosCallBack (GLFWwindow * pWin, double xpos, double ypos)
Definition at line 115 of file input.cpp.
 {
   mouse.x = xpos;
   mouse.y = ypos;
 }
Referenced by input::Init().