CSD2126: include/Mat3.h File Reference
Mat3.h File Reference
#include "Vec2.h"
Classes
struct Mat3
Functions
Mat3 operator* (const Mat3 &lhs, const Mat3 &rhs)
Vec2 operator* (const Mat3 &pMtx, const Vec2 &rhs)
Mat3 Mat3Identity ()
Mat3 Mat3Translate (float x, float y)
Mat3 Mat3Scale (float x, float y)
Mat3 Mat3RotRad (float angle)
Mat3 Mat3RotDeg (float angle)
Mat3 Mat3Transpose (const Mat3 &pMtx)
Mat3 Mat3Inverse (float *determinant, const Mat3 &pMtx)
Function Documentation
Mat3Identity()
Mat3 Mat3Identity ()
Definition at line 80 of file Mat3.cpp.
 {
   return Mat3({1.f, 0.f, 0.f, 0.f, 1.f, 0.f, 0.f, 0.f, 1.f});
 }
Mat3Inverse()
Mat3 Mat3Inverse (float * determinant, const Mat3 & pMtx)
Definition at line 110 of file Mat3.cpp.
 {
   *determinant = pMtx.m00 * ((pMtx.m11 * pMtx.m22) - (pMtx.m12 * pMtx.m21))
     - pMtx.m01 * ((pMtx.m10 * pMtx.m22) - (pMtx.m12 * pMtx.m20))
     + pMtx.m02 * ((pMtx.m10 * pMtx.m21) - (pMtx.m11 * pMtx.m20));
   if (!*determinant) {
     return NULL;
   }
   else {
     Mat3 pResult, tmp = Mat3Transpose(pMtx);
     pResult.m00 = ((tmp.m11 * tmp.m22) - (tmp.m12 * tmp.m21)) / *determinant;
     pResult.m01 = -((tmp.m10 * tmp.m22) - (tmp.m12 * tmp.m20)) / *determinant;
     pResult.m02 = ((tmp.m10 * tmp.m21) - (tmp.m11 * tmp.m20)) / *determinant;
     pResult.m10 = -((tmp.m01 * tmp.m22) - (tmp.m02 * tmp.m21)) / *determinant;
     pResult.m11 = ((tmp.m00 * tmp.m22) - (tmp.m02 * tmp.m20)) / *determinant;
     pResult.m12 = -((tmp.m00 * tmp.m21) - (tmp.m01 * tmp.m20)) / *determinant;
     pResult.m20 = ((tmp.m01 * tmp.m12) - (tmp.m02 * tmp.m11)) / *determinant;
     pResult.m21 = -((tmp.m00 * tmp.m12) - (tmp.m02 * tmp.m10)) / *determinant;
     pResult.m22 = ((tmp.m00 * tmp.m11) - (tmp.m01 * tmp.m10)) / *determinant;
     return pResult;
   }
 }
References Mat3::m00, Mat3::m01, Mat3::m02, Mat3::m10, Mat3::m11, Mat3::m12, Mat3::m20, Mat3::m21, Mat3::m22, and Mat3Transpose().
Mat3RotDeg()
Mat3 Mat3RotDeg (float angle)
Definition at line 100 of file Mat3.cpp.
 {
   return Mat3RotRad(angle * 3.14159265358f / 180.f);
 }
References Mat3RotRad().
Mat3RotRad()
Mat3 Mat3RotRad (float angle)
Definition at line 95 of file Mat3.cpp.
 {
   return Mat3({ float(cos(angle)), float(-sin(angle)), 0.f, float(sin(angle)), float(cos(angle)), 0.f, 0.f, 0.f, 1.f });
 }
Referenced by Mat3RotDeg().
Mat3Scale()
Mat3 Mat3Scale (float x, float y)
Definition at line 90 of file Mat3.cpp.
 {
   return Mat3({ x, 0.f, 0.f, 0.f, y, 0.f, 0.f, 0.f, 1.f });
 }
Mat3Translate()
Mat3 Mat3Translate (float x, float y)
Definition at line 85 of file Mat3.cpp.
 {
   return Mat3({ 1.f, 0.f, x, 0.f, 1.f, y, 0.f, 0.f, 1.f });
 }
Mat3Transpose()
Mat3 Mat3Transpose (const Mat3 & pMtx)
Definition at line 105 of file Mat3.cpp.
 {
   return Mat3({ pMtx.m00 , pMtx.m10, pMtx.m20, pMtx.m01, pMtx.m11, pMtx.m21, pMtx.m02, pMtx.m12, pMtx.m22 });
 }
References Mat3::m00, Mat3::m01, Mat3::m02, Mat3::m10, Mat3::m11, Mat3::m12, Mat3::m20, Mat3::m21, and Mat3::m22.
Referenced by Mat3Inverse().
operator*() [1/2]
Mat3 operator* (const Mat3 & lhs, const Mat3 & rhs)
Definition at line 58 of file Mat3.cpp.
 {
   float m[3][3]{};
   for (int i = 0; i < 3; i++)
     for (int j = 0; j < 3; j++)
       for (int k = 0; k < 3; k++)
         m[i][j] += lhs.m2[i][k] * rhs.m2[k][j];
   float m2[9]{};
   for (int i = 0; i < 9; i++)
     m2[i] = m[i / 3][i % 3];
   return Mat3(m2);
 }
References Mat3::m2.
operator*() [2/2]
Vec2 operator* (const Mat3 & pMtx, const Vec2 & rhs)
Definition at line 75 of file Mat3.cpp.
 {
   return Vec2(pMtx.m00 * rhs.x + pMtx.m01 * rhs.y + pMtx.m02, pMtx.m10 * rhs.x + pMtx.m11 * rhs.y + pMtx.m12);
 }
References Mat3::m00, Mat3::m01, Mat3::m02, Mat3::m10, Mat3::m11, Mat3::m12, Vec2::x, and Vec2::y.