CSD2126: input Namespace Reference
input Namespace Reference
Functions
bool IsPressed (KEY)
bool IsPressedRepeatedly (KEY)
bool IsReleased (KEY)
double GetMouseX ()
double GetMouseY ()
void Init (GLFWwindow *pWin)
Function Documentation
GetMouseX()
double input::GetMouseX ()
returns x position of mouse.
Definition at line 146 of file input.cpp.
 {
   return mouse.x;
 }
GetMouseY()
double input::GetMouseY ()
returns y position of mouse.
Definition at line 150 of file input.cpp.
 {
   return mouse.y;
 }
Init()
void input::Init (GLFWwindow * pWin)
for use in graphics.cpp to initialise GLFW callbacks
Definition at line 121 of file input.cpp.
 {
   glfwSetKeyCallback(pWin, KeyCallBack);
   glfwSetMouseButtonCallback(pWin, MouseButtonCallBack);
   glfwSetCursorPosCallback(pWin, MousePosCallBack);
 }
References KeyCallBack(), MouseButtonCallBack(), and MousePosCallBack().
Referenced by GLWindow::Initialize().
IsPressed()
bool input::IsPressed (KEY key)
returns true if key is triggered for the first time after released. If key is held down for more than 1 game loop, return false.
Definition at line 129 of file input.cpp.
 {
   return buttons[at(key)].IsPressed();
 }
References at().
IsPressedRepeatedly()
bool input::IsPressedRepeatedly (KEY key)
returns true as long as key is held down for more than 1 game loop.
Definition at line 141 of file input.cpp.
 {
   return buttons[at(key)].IsPressedRepeatedly();
 }
References at().
IsReleased()
bool input::IsReleased (KEY)
returns true if key is not pressed/pressedrepeatedly