CSD2126: AABB Struct Reference
AABB Struct Reference
#include <AABB.h>
Public Member Functions
Vec2 P0 () const
Vec2 P1 () const
Vec2 P2 () const
Vec2 P3 () const
Public Attributes
Vec2 min
Vec2 max
Detailed Description
Definition at line 5 of file AABB.h.
Member Function Documentation
P0()
Vec2 AABB::P0 () const inline
Definition at line 17 of file AABB.h.
 { return min; } // Bottom Left
References min.
Referenced by Collision::Check_AABB_Line().
P1()
Vec2 AABB::P1 () const inline
Definition at line 18 of file AABB.h.
 { return { max.x, min.y }; } // Bottom Right
References max, min, Vec2::x, and Vec2::y.
Referenced by Collision::Check_AABB_Line().
P2()
Vec2 AABB::P2 () const inline
Definition at line 19 of file AABB.h.
 { return max; } // Top Right
References max.
Referenced by Collision::Check_AABB_Line().
P3()
Vec2 AABB::P3 () const inline
Definition at line 20 of file AABB.h.
 { return { min.x, max.y }; } // Top Left
References max, min, Vec2::x, and Vec2::y.
Referenced by Collision::Check_AABB_Line().
Member Data Documentation
max
Vec2 AABB::max
Definition at line 8 of file AABB.h.
Referenced by Collision::Check_AABB_AABB(), P1(), P2(), and P3().
min
Vec2 AABB::min
Definition at line 7 of file AABB.h.
Referenced by Collision::Check_AABB_AABB(), P0(), P1(), and P3().
The documentation for this struct was generated from the following file:
include/AABB.h