CSD2126: include/Vec2.h File Reference
Vec2.h File Reference
#include <glm/glm.hpp>
Classes
struct Vec2
Functions
Vec2 operator+ (const Vec2 &lhs, const Vec2 &rhs)
Vec2 operator- (const Vec2 &lhs, const Vec2 &rhs)
Vec2 operator* (const Vec2 &lhs, float rhs)
Vec2 operator* (float lhs, const Vec2 &rhs)
Vec2 operator/ (const Vec2 &lhs, float rhs)
Vec2 Vec2Normalize (const Vec2 &pVec0)
float Vec2Length (const Vec2 &pVec0)
float Vec2SquareLength (const Vec2 &pVec0)
float Vec2Distance (const Vec2 &pVec0, const Vec2 &pVec1)
float Vec2SquareDistance (const Vec2 &pVec0, const Vec2 &pVec1)
float Vec2DotProduct (const Vec2 &pVec0, const Vec2 &pVec1)
float Vec2CrossProductMag (const Vec2 &pVec0, const Vec2 &pVec1)
Function Documentation
operator*() [1/2]
Vec2 operator* (const Vec2 & lhs, float rhs)
Definition at line 58 of file Vec2.cpp.
 {
   return Vec2(lhs.x * rhs, lhs.y * rhs);
 }
References Vec2::x, and Vec2::y.
operator*() [2/2]
Vec2 operator* (float lhs, const Vec2 & rhs)
Definition at line 63 of file Vec2.cpp.
 {
   return Vec2(lhs * rhs.x, lhs * rhs.y);
 }
References Vec2::x, and Vec2::y.
operator+()
Vec2 operator+ (const Vec2 & lhs, const Vec2 & rhs)
Definition at line 48 of file Vec2.cpp.
 {
   return Vec2(lhs.x + rhs.x, lhs.y + rhs.y);
 }
References Vec2::x, and Vec2::y.
operator-()
Vec2 operator- (const Vec2 & lhs, const Vec2 & rhs)
Definition at line 53 of file Vec2.cpp.
 {
   return Vec2(lhs.x - rhs.x, lhs.y - rhs.y);
 }
References Vec2::x, and Vec2::y.
operator/()
Vec2 operator/ (const Vec2 & lhs, float rhs)
Definition at line 68 of file Vec2.cpp.
 {
   return Vec2(lhs.x / rhs, lhs.y / rhs);
 }
References Vec2::x, and Vec2::y.
Vec2CrossProductMag()
float Vec2CrossProductMag (const Vec2 & pVec0, const Vec2 & pVec1)
Definition at line 110 of file Vec2.cpp.
 {
   return pVec0.x * pVec1.y - pVec0.y * pVec1.x;
 }
References Vec2::x, and Vec2::y.
Vec2Distance()
float Vec2Distance (const Vec2 & pVec0, const Vec2 & pVec1)
Definition at line 93 of file Vec2.cpp.
 {
   Vec2 distance{ pVec1.x - pVec0.x, pVec1.y - pVec0.y };
   return Vec2Length(distance);
 }
References Vec2Length(), Vec2::x, and Vec2::y.
Vec2DotProduct()
float Vec2DotProduct (const Vec2 & pVec0, const Vec2 & pVec1)
Definition at line 105 of file Vec2.cpp.
 {
   return pVec1.x * pVec0.x + pVec1.y * pVec0.y;
 }
References Vec2::x, and Vec2::y.
Referenced by Collision::Check_AABB_Line(), Collision::Check_Circle_Line(), Collision::Check_Circle_LineEdge(), and Collision::Response_Object_Line().
Vec2Length()
float Vec2Length (const Vec2 & pVec0)
Definition at line 83 of file Vec2.cpp.
 {
   return sqrt(pVec0.x * pVec0.x + pVec0.y * pVec0.y);
 }
References Vec2::x, and Vec2::y.
Referenced by Collision::Check_Circle_LineEdge(), Collision::Response_Object_Line(), Vec2Distance(), Vec2Normalize(), Vec2SquareDistance(), and Vec2SquareLength().
Vec2Normalize()
Vec2 Vec2Normalize (const Vec2 & pVec0)
Definition at line 77 of file Vec2.cpp.
 {
   float f = Vec2Length(pVec0);
   return Vec2(pVec0.x / f, pVec0.y / f);
 }
References Vec2Length(), Vec2::x, and Vec2::y.
Referenced by Collision::Check_AABB_Line(), Collision::Check_Circle_Line(), Collision::Check_Circle_LineEdge(), and Collision::Response_Object_Line().
Vec2SquareDistance()
float Vec2SquareDistance (const Vec2 & pVec0, const Vec2 & pVec1)
Definition at line 99 of file Vec2.cpp.
 {
   Vec2 distance{ pVec1.x - pVec0.x, pVec1.y - pVec0.y };
   return Vec2Length(distance) * Vec2Length(distance);
 }
References Vec2Length(), Vec2::x, and Vec2::y.
Vec2SquareLength()
float Vec2SquareLength (const Vec2 & pVec0)
Definition at line 88 of file Vec2.cpp.
 {
   return Vec2Length(pVec0) * Vec2Length(pVec0);
 }
References Vec2Length().